import { IBubbleWithoutPosition, PadBubblePositions } from './_shared';

const bubbleData: IBubbleWithoutPosition[] = [
	{
		id: 'about',
		name: 'About Epic Colors',
		summary: 'Epic Colors is an Among Us cosmetics mod. Players could change their character\'s color.',
		image: 'epic-colors',
		connection: '.',
		position: [50, 50],
		pivotPosition: [50, 50],
		deployPosition: [50, 50],
		radius: 105,
		size: 'large',
	},
	{
		id: 'image',
		name: 'Epic Colors Image',
		image: 'epic-colors-example',
		connection: 'about',
		radius: 100,
	},
	{
		id: 'devsUs',
		name: 'Devs Us',
		summary: 'This was developed by the open-source developer community, Devs Us.',
		link: 'devs-us',
		image: 'devs-us',
		connection: 'about',
		radius: 91,
		size: 'medium',
	},
	{
		id: 'development',
		name: 'Development Info',
		summary: 'The mod was built on Reactor, an Among Us modding API. Reactor was built on BepInEx, a Unity game patcher. BepInEx was built on Harmony, a C# patcher.',
		link: 'https://github.com/Devs-Us/EpicColors',
		connection: 'about',
		radius: 119,
		size: 'medium',
	},
	{
		id: 'contribution',
		name: 'My Contributions',
		summary: 'I was a major GitHub contributor. I introduced a variety of features.',
		connection: 'about',
		radius: 100,
		size: 'medium',
	},
	{
		id: 'refactor',
		name: 'Refactor',
		summary: 'To make it a lot easier to add new colors, I introduced a reusable way to add colors. I moved everything from arrays, to classes.',
		connection: 'contribution',
		radius: 98,
		size: 'small',
	},
	{
		id: 'autoBuild',
		name: 'Auto Template',
		summary: 'Before our team introduced a feature allowing everyone to make a template of their favorite colors. I foresaw some minor issues, particularly with ease-of-use. Solution: I made the template build automatically.',
		connection: 'contribution',
		radius: 125,
		size: 'small',
	},
	{
		id: 'animated',
		name: 'Animated Colors',
		summary: 'To make Epic Colors stand out, we introduced animated colors that provides a lot more personality.',
		connection: 'contribution',
		radius: 105,
		size: 'medium',
	},
];

export default PadBubblePositions('epic-colors', bubbleData);