import { IBubbleWithoutPosition, PadBubblePositions } from './_shared';

const bubbleData: IBubbleWithoutPosition[] = [
	{
		id: 'about',
		name: 'About Sorting Visualizer',
		summary: 'Sorting visualizer gives it\'s users a chance to learn how sorting algorithms work.',
		image: 'sorting-algorithm-visualizer',
		connection: '.',
		position: [50, 50],
		pivotPosition: [50, 50],
		deployPosition: [50, 50],
		radius: 110,
		size: 'large',
	},
	{
		id: 'image',
		name: 'Sorting Algorithm Visualizer Webpage',
		link: 'https://sorting-algorithm-jet.vercel.app/',
		image: 'sorting-algorithm-visualizer-page',
		connection: 'about',
		radius: 100,
	},
	{
		id: 'accomplishments',
		name: 'Accomplishments',
		summary: 'This website proves that innovation could originate from common programming projects.',
		connection: 'about',
		radius: 104,
		size: 'medium',
	},
	{
		id: 'features',
		name: 'Exclusive Features',
		summary: 'Only visualizer I have seen that generates a history graph (and so much more)!',
		image: 'quick-sort',
		connection: 'accomplishments',
		radius: 97,
		size: 'small',
	},
	{
		id: 'lighthouse',
		name: 'Impressive Performance',
		summary: 'Both page performance, and graph rendering run well against the most challenging computers.',
		connection: 'accomplishments',
		radius: 103,
		size: 'small',
	},
	{
		id: 'dynamic',
		name: 'Dynamic',
		summary: 'Uses file-based routing for most settings, new algorithms can be added by writing a file.',
		connection: 'accomplishments',
		radius: 98,
		size: 'small',
	},
	{
		id: 'development',
		name: 'Development Info',
		summary: 'Sorting Algorithm Visualizer is an open source project.',
		connection: 'about',
		radius: 96,
		size: 'medium',
	},
	{
		id: 'framework',
		name: 'Frameworks',
		summary: 'The website is built on Angular.',
		connection: 'development',
		radius: 80,
		size: 'small',
	},
	{
		id: 'concepts',
		name: 'Code Concepts',
		summary: 'Users are given options to visualize arrays with lengths of up to thousands. Optimization is essential, however, it readability and reusability was number one.',
		connection: 'development',
		radius: 118,
		size: 'small',
	},
	{
		id: 'sorts',
		name: 'Sorting Algorithms',
		summary: 'There are 18+ sorting algorithms to choose from.',
		connection: 'about',
		radius: 94,
		size: 'medium',
	},
	{
		id: 'quickSort',
		name: 'Quick Sort',
		image: 'quick-sort',
		connection: 'sorts',
		radius: 93,
		size: 'small',
	},
	{
		id: 'radixSort',
		name: 'Radix Sort',
		image: 'radix-sort',
		connection: 'sorts',
		radius: 80,
		size: 'small',
	},
	{
		id: 'bogoSort',
		name: 'Bogo Sort',
		image: 'bogo-sort',
		connection: 'sorts',
		radius: 80,
		size: 'small',
	},
	{
		id: 'sleepSort',
		name: 'Sleep Sort',
		image: 'sleep-sort',
		connection: 'sorts',
		radius: 83,
		size: 'small',
	},
	{
		id: 'bubbleSort',
		name: 'Bubble Sort',
		image: 'bubble-sort',
		connection: 'sorts',
		radius: 83,
		size: 'small',
	},
	{
		id: 'heapSort',
		name: 'Heap Sort',
		image: 'heap-sort',
		connection: 'sorts',
		radius: 81,
		size: 'small',
	},
];

export default PadBubblePositions('sorting-algorithm-visualizer', bubbleData);