import { IBubbleWithoutPosition, PadBubblePositions } from './_shared';

const bubbleData: IBubbleWithoutPosition[] = [
	{
		id: 'about',
		name: 'About Sparrow Design',
		summary: 'Sparrow Design is a small web and mobile development agency working with many clients, small and large.',
		connection: '.',
		position: [50, 50],
		pivotPosition: [50, 50],
		deployPosition: [50, 50],
		radius: 112,
		size: 'large',
	},
	{
		id: 'image',
		name: 'Sparrow Design logo',
		image: 'sparrow-design',
		connection: 'about',
		radius: 100,
	},
	{
		id: 'worklife',
		name: 'Life Working At Sparrow Design',
		summary: 'I enjoyed working at Sparrow Design a lot.',
		connection: 'about',
		radius: 98,
		size: 'medium',
	},
	{
		id: 'inPerson',
		name: 'In Person',
		summary: 'I love having an office to work at. At Sparrow Design, I worked with the same few employees in an office. We bonded greatly together.',
		connection: 'worklife',
		radius: 102,
		size: 'small',
	},
	{
		id: 'learning',
		name: 'Learning',
		summary: 'At Sparrow Design I was given an opportunity to learn new technologies. I quickly became efficient with the tools within days or weeks.',
		connection: 'worklife',
		radius: 101,
		size: 'small',
	},
	{
		id: 'duties',
		name: 'Duties',
		summary: 'I had a small but valuable amount of freedom. I was able to become productive by switching between tasks whenever a task became unexpectedly exhausting.',
		connection: 'worklife',
		radius: 112,
		size: 'small',
	},
	{
		id: 'accomplishments',
		name: 'Accomplishments',
		summary: 'During my time at Sparrow Design, I accomplished many things. Here are some of the most important accomplishments.',
		connection: 'about',
		radius: 113,
		size: 'medium',
	},
	{
		id: 'youtubeClient',
		name: 'Youtuber Client',
		summary: 'Developed mobile applications for a 3,000,000+ subscriber YouTuber.',
		connection: 'accomplishments',
		radius: 101,
		size: 'small',
	},
	{
		id: 'improvedCode',
		name: 'Improved Code Style',
		summary: 'Reduced code bloat by 75% in some areas while improving readability with reuseable methods',
		connection: 'accomplishments',
		radius: 106,
		size: 'small',
	},
	{
		id: 'clientRecognition',
		name: 'Client Recognition',
		summary: 'Received written compliments from clients for exceptional work and quick turnaround times.',
		connection: 'accomplishments',
		radius: 107,
		size: 'small',
	},
];

export default PadBubblePositions('sparrow-design', bubbleData);