import { IBubbleWithoutPosition, PadBubblePositions } from './_shared';

const bubbleData: IBubbleWithoutPosition[] = [
	{
		id: 'about',
		name: 'About YSK Kyle',
		summary: 'YSK Kyle is my portfolio website to display my experience with website design.',
		image: 'ysk-kyle',
		connection: '.',
		position: [50, 50],
		pivotPosition: [50, 50],
		deployPosition: [50, 50],
		radius: 103,
		size: 'large',
	},
	{
		id: 'image',
		name: 'YSK Kyle Webpage',
		image: 'ysk-kyle-page',
		link: 'https://www.yskkyle.com/',
		connection: 'about',
		radius: 100,
	},
	{
		id: 'accomplishments',
		name: 'Accomplishments',
		summary: 'Developed in a few weeks, YSK Kyle achieves a lot.',
		connection: 'about',
		radius: 103,
		size: 'medium',
	},
	{
		id: 'testedAndCommented',
		name: 'Well Tested and Commented',
		summary: 'Years after development, the codebase was easy to safely come back and add features.',
		connection: 'accomplishments',
		radius: 107,
		size: 'small',
	},
	{
		id: 'dynamic',
		name: 'Dynamic',
		summary: 'To create new pages or settings, all I need is to add a JSON file into a directory.',
		connection: 'accomplishments',
		radius: 87,
		size: 'small',
	},
	{
		id: 'highlyPerformant',
		name: 'Highly Performant',
		summary: 'Average load times on very low performance settings.',
		connection: 'accomplishments',
		radius: 91,
		size: 'small',
	},
	{
		id: 'developmentInfo',
		name: 'Development Info',
		summary: 'The code behind YSK Kyle is visible on GitHub. The repository does not allow contributions.',
		link: 'https://github.com/KyleSmith0905',
		connection: 'about',
		radius: 112,
		size: 'medium',
	},
	{
		id: 'framework',
		name: 'Framework',
		summary: 'YSK Kyle was built with React and Next.',
		connection: 'developmentInfo',
		radius: 87,
		size: 'small',
	},
	{
		id: 'particleEngine',
		name: 'The Particle Engine',
		summary: 'The bubbles were simulated using a quick particle engine I wrote.',
		connection: 'developmentInfo',
		radius: 103,
		size: 'small',
	},
	{
		id: 'updateProfile',
		name: 'Update Profile',
		summary: 'A script running from YSKKyle updates my avatars on my social media profiles. I have learned a lot from working natively with many different APIs.',
		connection: 'about',
		radius: 109,
		size: 'medium',
	},
];

export default PadBubblePositions('ysk-kyle', bubbleData);